# Generated by Django 2.2.7 on 2020-03-19 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='user_id')),
                ('user_name', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('user_type', models.IntegerField(choices=[(1, 'user'), (6, 'admin')], verbose_name='用户类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键ID')),
                ('user_token', models.CharField(max_length=64, verbose_name='用户Token')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_user', to='DjangoRESTFramework.UserInfo', verbose_name='一对一用户关联')),
            ],
        ),
        migrations.CreateModel(
            name='UserProject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键ID')),
                ('name', models.CharField(max_length=50, verbose_name='项目名称')),
                ('description', models.CharField(max_length=1024, null=True, verbose_name='描述')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_project', to='DjangoRESTFramework.UserInfo', verbose_name='一对多用户关联')),
            ],
        ),
        migrations.CreateModel(
            name='UserApiInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键ID')),
                ('url', models.CharField(max_length=1024, verbose_name='接口名称')),
                ('method', models.CharField(max_length=32, verbose_name='请求方法(GET, POST)')),
                ('data', models.CharField(max_length=1024, verbose_name='接口数据')),
                ('headers', models.CharField(max_length=1024, verbose_name='请求头')),
                ('expectedresults', models.CharField(blank=True, max_length=64, null=True, verbose_name='预期结果')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_info', to='DjangoRESTFramework.UserProject', verbose_name='所属项目')),
            ],
        ),
    ]
