# Generated by Django 2.2.7 on 2020-04-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoRESTFramework', '0002_auto_20200401_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapiinfo',
            name='resultsave',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='接口结果'),
        ),
    ]
