# Generated by Django 2.2.7 on 2020-04-03 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoRESTFramework', '0004_auto_20200403_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapiinfo',
            name='founder',
            field=models.IntegerField(verbose_name='创建人'),
        ),
    ]
