# Generated by Django 2.2.7 on 2020-04-03 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoRESTFramework', '0005_auto_20200403_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapiinfo',
            name='founder',
        ),
        migrations.AddField(
            model_name='userapiinfo',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_api', to='DjangoRESTFramework.UserInfo', verbose_name='一对多用户关联'),
            preserve_default=False,
        ),
    ]
