# Generated by Django 2.2.7 on 2020-04-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoRESTFramework', '0007_auto_20200408_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapiinfo',
            name='data',
            field=models.CharField(max_length=1024, verbose_name='接口数据'),
        ),
        migrations.AlterField(
            model_name='userapiinfo',
            name='headers',
            field=models.CharField(max_length=1024, verbose_name='请求头'),
        ),
    ]
