# Generated by Django 2.2.7 on 2020-04-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoRESTFramework', '0008_auto_20200408_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapool',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='主键ID'),
        ),
    ]
