# Generated by Django 2.2.7 on 2020-04-14 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoRESTFramework', '0010_auto_20200413_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadersPool',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键ID')),
                ('datakey', models.CharField(max_length=64, verbose_name='数据key')),
                ('datavalue', models.CharField(max_length=64, verbose_name='数据value')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='描述')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers_pool', to='DjangoRESTFramework.UserInfo', verbose_name='创建人')),
            ],
        ),
    ]
